info:
  app:
    name: sports-order
    description: Microloans service
  team:
    name: D2 team

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  application:
    name: sports-order
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  liquibase:
    liquibaseSchema: migration
    change-log: classpath:/db/changelog/master.yml

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_schema: application

springdoc:
  api-docs:
    enabled: true
    path: /sports-order/v3/api-docs


server:
  port: ${PORT:8381}