spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sports_fight}
    username: ${DB_USER:username}
    password: ${DB_PASSWORD:password}

  cloud:
    config:
      enabled: false
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic
      sports-order:
        name: ${SPORTS_ORDER_NAME:sports-order}
        url: ${SPORTS_ORDER_URL:localhost:8381}

  kafka:
    bootstrap-servers: localhost:29092, localhost:29093, localhost:29094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topics:
      notification-email-topic: sports-notification-email-topic

eureka:
  client:
    enabled: false

api:
  job:
    scheduler:
      process-debt: "0 */5 * * * *"

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: always