POST http://localhost:8080/api/v2/auth
Content-Type: application/json

{
  "username": "customer2",
  "password": "customer2",
  "nick": "customer2",
  "telegram": "customer2",
  "role": "CUSTOMER"
}
###

POST http://localhost:8080/api/v2/auth/tokens
Content-Type: application/json

{
  "username": "customer2",
  "password": "customer2"
}

###

  "id": "dbc0ce06-c43c-4110-a4b9-4a9cb9e80ac0",
"username": "customer2",
"access": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjdXN0b21lcjIiLCJpZCI6ImRiYzBjZTA2LWM0M2MtNDExMC1hNGI5LTRhOWNiOWU4MGFjMCIsInJvbGVzIjpbIkNVU1RPTUVSIl0sImV4cCI6MTczMjQ4NDg4NH0.qqXRusZh6H7Nt8iBOVkVOD1UeyvfgsTry_CJ5zYXt8hJR-ePg501rVvgcpkdZ24lMQb2fvcn_c8W3tAZ13q8Uw",
"refresh": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjdXN0b21lcjIiLCJpZCI6ImRiYzBjZTA2LWM0M2MtNDExMC1hNGI5LTRhOWNiOWU4MGFjMCIsImV4cCI6MTczMjU2NzY4NH0.L41p1Sa7Xdp0Mrs_RBOx9xrNLVZE-3L8py3IFPGJ2dXqw_U858cZEBvKiQIWUfjl20nltO5Q24tAi8tILW_eow"
}

###

POST http://localhost:8080/api/v2/cities
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjdXN0b21lcjIiLCJpZCI6IjgyMDAxZGFiLTY1MzMtNDBlNS04ZDI3LTEwNTFjY2QyZDhmYSIsInJvbGVzIjpbIkNVU1RPTUVSIl0sImV4cCI6MTczMjUzMjQzM30.WzpgoycqOevny3aF4qP8d0aEbpKI6Bq5SUC-fmfScbhgAONWH_BUujwLX8kKzxRvEH5opnhlUFYyEQpbvO7Rag


{
  "name": "city2",
  "region": "region2"
}


###

GET http://localhost:8080/api/v2/cities
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjdXN0b21lcjIiLCJpZCI6ImI0MDFlOWNjLTMwZTItNGRjOC1hNTE5LWE3ZjAyOWQzNjQ2MSIsInJvbGVzIjpbIkNVU1RPTUVSIl0sImV4cCI6MTczMjU1MDU0OH0.8TN_UucFmOobVn7_ZjMG9lv95xWByTcbdNxIgIWZ17wR5xkRBQY599dxBzgissDhwCdFDUBk4EBJnpUk_p8EqA

###

GET http://localhost:8080/api/v2/mutilations
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjdXN0b21lcjIiLCJpZCI6ImI0MDFlOWNjLTMwZTItNGRjOC1hNTE5LWE3ZjAyOWQzNjQ2MSIsInJvbGVzIjpbIkNVU1RPTUVSIl0sImV4cCI6MTczMjU1MDU0OH0.8TN_UucFmOobVn7_ZjMG9lv95xWByTcbdNxIgIWZ17wR5xkRBQY599dxBzgissDhwCdFDUBk4EBJnpUk_p8EqA

###


GET http://localhost:8080/api/v2/victims
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjdXN0b21lcjIiLCJpZCI6ImI0MDFlOWNjLTMwZTItNGRjOC1hNTE5LWE3ZjAyOWQzNjQ2MSIsInJvbGVzIjpbIkNVU1RPTUVSIl0sImV4cCI6MTczMjU1MDU0OH0.8TN_UucFmOobVn7_ZjMG9lv95xWByTcbdNxIgIWZ17wR5xkRBQY599dxBzgissDhwCdFDUBk4EBJnpUk_p8EqA

###
POST http://localhost:8080/api/v2/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjdXN0b21lcjIiLCJpZCI6ImI0MDFlOWNjLTMwZTItNGRjOC1hNTE5LWE3ZjAyOWQzNjQ2MSIsInJvbGVzIjpbIkNVU1RPTUVSIl0sImV4cCI6MTczMjU1MDU0OH0.8TN_UucFmOobVn7_ZjMG9lv95xWByTcbdNxIgIWZ17wR5xkRBQY599dxBzgissDhwCdFDUBk4EBJnpUk_p8EqA


{
  "cityId": "d4300397-ec4b-499d-8ebe-fa7b6cc26683",
  "victimId": "877bbfad-eb31-427a-891b-103ff674f12d",
  "deadline": "2024-12-01",
  "mutilationIds": ["52b9df28-92d3-4481-b7f0-193f31aa037a"]
}

###
