services:

  sports-postgres:
    container_name: sports-postgres
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - ./init_databases.sql:/docker-entrypoint-initdb.d/init_databases.sql
    profiles:
      - cloud
      - local

  sports-minio:
    container_name: sports-minio
    image: bitnami/minio:2024
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: username
      MINIO_ROOT_PASSWORD: password
      MINIO_DEFAULT_BUCKETS: sports-file
    profiles:
      - cloud
      - local

  sports-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: sports-zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  sports-kafka-broker-1:
    image: confluentinc/cp-kafka:latest
    container_name: sports-kafka-broker-1
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: sports-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://sports-kafka-broker-1:9092, PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
    depends_on:
      - sports-zookeeper

  sports-kafka-broker-2:
    image: confluentinc/cp-kafka:latest
    container_name: sports-kafka-broker-2
    ports:
      - "9093:9093"
      - "29093:29093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: sports-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://sports-kafka-broker-2:9093, PLAINTEXT_HOST://localhost:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
    depends_on:
      - sports-zookeeper

  sports-kafka-broker-3:
    image: confluentinc/cp-kafka:latest
    container_name: sports-kafka-broker-3
    ports:
      - "9094:9094"
      - "29094:29094"
    depends_on:
      - sports-zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: sports-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://sports-kafka-broker-3:9094, PLAINTEXT_HOST://localhost:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT

  sports-discovery:
    container_name: sports-discovery
    image: sports-discovery
    ports:
      - "8761:8761"
    build:
      context: "sports-discovery"
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      EUREKA_CLIENT_USERNAME: eureka_client
      EUREKA_CLIENT_PASSWORD: eureka_password
      PORT: 8761
    profiles:
      - cloud

  sports-config:
    container_name: sports-config
    image: sports-config
    ports:
      - "8888:8888"
    build:
      context: "sports-config"
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: native
      DISCOVERY_SERVER_URL: http://eureka_client:eureka_password@sports-discovery:8761/eureka
      PORT: 8888

      SPORTS_USER_NAME: sports-user
      SPORTS_ORDER_NAME: sports_order
      SPORTS_FIGHT_NAME: sports_fight

      # sports-user
      SPORTS_USER_R2DBC_URL: r2dbc:postgresql://sports-postgres:5432/sports_user
      SPORTS_USER_JDBC_URL: jdbc:postgresql://sports-postgres:5432/sports_user
      SPORTS_USER_DB_USER: username
      SPORTS_USER_DB_PASSWORD: password
      SECRET: aGZiYmtiYWllYmNpZWFpZWJsZWNldWNlY2xhZWNhaWJlbGNhZWN3Q0VCV0VXSUM=
      ACCESS: 1
      REFRESH: 24
       # sports-order
      SPORTS_ORDER_JDBC_URL: jdbc:postgresql://sports-postgres:5432/sports_order
      SPORTS_ORDER_DB_USER: username
      SPORTS_ORDER_DB_PASSWORD: password
      # sports-fight
      SPORTS_FIGHT_JDBC_URL: jdbc:postgresql://sports-postgres:5432/sports_fight
      SPORTS_FIGHT_DB_USER: username
      SPORTS_FIGHT_DB_PASSWORD: password
      SPORTS_ORDER_URL: sports_order
      # sports-file
      MINIO_ENDPOINT: http://sports-minio:9000
      MINIO_ACCESS_KEY: username
      MINIO_SECRET_KEY: password
      MINIO_BUCKET: sports-file
      MINIO_REGION: us-east-1
    depends_on:
      - sports-discovery
    profiles:
      - cloud

  sports-admin:
    container_name: sports-admin
    image: sports-admin
    ports:
      - "8187:8187"
    build:
      context: "sports-admin"
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      DISCOVERY_SERVER_URL: http://eureka_client:eureka_password@sports-discovery:8761/eureka
      PORT: 8187
    depends_on:
      - sports-discovery
      - sports-config
    profiles:
      - cloud

  sports-gateway:
    container_name: sports-gateway
    image: sports-gateway
    ports:
      - "8080:8080"
    build:
      context: "sports-gateway"
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      DISCOVERY_SERVER_URL: http://eureka_client:eureka_password@sports-discovery:8761/eureka
      API_PREFIX: /api/v3
      PORT: 8080
    depends_on:
      - sports-discovery
      - sports-config
    profiles:
      - cloud

  sports-user:
    container_name: sports-user
    image: sports-user
    ports:
      - "8383:8383"
    build:
      context: "sports-user"
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      DISCOVERY_SERVER_URL: http://eureka_client:eureka_password@sports-discovery:8761/eureka
      PORT: 8383
    depends_on:
      - sports-postgres
      - sports-discovery
      - sports-config
      - sports-gateway
    profiles:
      - cloud

  sports-order:
    container_name: sports-order
    image: sports-order
    ports:
      - "8381:8381"
    build:
      context: "sports-order"
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      DISCOVERY_SERVER_URL: http://eureka_client:eureka_password@sports-discovery:8761/eureka
      PORT: 8381
    depends_on:
      - sports-postgres
      - sports-discovery
      - sports-config
      - sports-gateway
    profiles:
      - cloud

  sports-fight:
    container_name: sports-fight
    image: sports-fight
    ports:
      - "8387:8387"
    build:
      context: "sports-fight"
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      DISCOVERY_SERVER_URL: http://eureka_client:eureka_password@sports-discovery:8761/eureka
      PORT: 8387
    depends_on:
      - sports-postgres
      - sports-discovery
      - sports-config
      - sports-gateway
      - sports-kafka-broker-1
      - sports-kafka-broker-2
      - sports-kafka-broker-3
    profiles:
      - cloud

  sports-file:
    container_name: sports-file
    image: sports-file
    ports:
      - "8389:8389"
    build:
      context: "sports-file"
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      DISCOVERY_SERVER_URL: http://eureka_client:eureka_password@sports-discovery:8761/eureka
      PORT: 8389
    depends_on:
      - sports-minio
      - sports-discovery
      - sports-config
      - sports-gateway
    profiles:
      - cloud