services:

  sports-postgres:
    container_name: sports-postgres
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - ./init_databases.sql:/docker-entrypoint-initdb.d/init_databases.sql
    profiles:
      - cloud
      - local

  sports-discovery:
    container_name: sports-discovery
    image: sports-discovery
    ports:
      - "8761:8761"
    build:
      context: "sports-discovery"
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      EUREKA_CLIENT_USERNAME: eureka_client
      EUREKA_CLIENT_PASSWORD: eureka_password
      PORT: 8761
    profiles:
      - cloud

  sports-config:
    container_name: sports-config
    image: sports-config
    ports:
      - "8888:8888"
    build:
      context: "sports-config"
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: native
      DISCOVERY_SERVER_URL: http://eureka_client:eureka_password@sports-discovery:8761/eureka
      PORT: 8888

      SPORTS_USER_NAME: sports-user
#        SPORTS_ORDER_NAME: sports_order
#        SPORTS_PROCESS_NAME: sports-process
      # sports-user
      SPORTS_USER_R2DBC_URL: r2dbc:postgresql://sports-postgres:5432/sports_user
      SPORTS_USER_JDBC_URL: jdbc:postgresql://sports-postgres:5432/sports_user
      SPORTS_USER_DB_USER: username
      SPORTS_USER_DB_PASSWORD: password
      SECRET: aGZiYmtiYWllYmNpZWFpZWJsZWNldWNlY2xhZWNhaWJlbGNhZWN3Q0VCV0VXSUM=
      ACCESS: 1
      REFRESH: 24
      # afa-order
#        AFA_ORDER_JDBC_URL: jdbc:postgresql://sports-postgres:5432/sports_order
#        AFA_ORDER_DB_USER: username
#        AFA_ORDER_DB_PASSWORD: password
      # sports-process
#        AFA_PROCESS_JDBC_URL: jdbc:postgresql://sports-postgres:5432/sports_process
#        AFA_PROCESS_DB_USER: username
#        AFA_PROCESS_DB_PASSWORD: password
#        AFA_ORDER_URL: sports_order

    depends_on:
      - sports-discovery
    profiles:
      - cloud

  sports-admin:
    container_name: sports-admin
    image: sports-admin
    ports:
      - "8187:8187"
    build:
      context: "sports-admin"
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      DISCOVERY_SERVER_URL: http://eureka_client:eureka_password@sports-discovery:8761/eureka
      PORT: 8187
    depends_on:
      - sports-discovery
      - sports-config
    profiles:
      - cloud

  sports-gateway:
    container_name: sports-gateway
    image: sports-gateway
    ports:
      - "8080:8080"
    build:
      context: "sports-gateway"
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      DISCOVERY_SERVER_URL: http://eureka_client:eureka_password@sports-discovery:8761/eureka
      API_PREFIX: /api/v2
      PORT: 8080
    depends_on:
      - sports-discovery
      - sports-config
    profiles:
      - cloud

  sports-user:
    container_name: sports-user
    image: sports-user
    ports:
      - "8383:8383"
    build:
      context: "sports-user"
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      DISCOVERY_SERVER_URL: http://eureka_client:eureka_password@sports-discovery:8761/eureka
      PORT: 8383
    depends_on:
      - sports-postgres
      - sports-discovery
      - sports-config
      - sports-gateway
    profiles:
      - cloud

#    sports-order:
#      container_name: sports-order
#      image: sports-order
#      ports:
#        - "8381:8381"
#      build:
#        context: "sports-order"
#        dockerfile: Dockerfile
#      environment:
#        SPRING_PROFILES_ACTIVE: cloud
#        DISCOVERY_SERVER_URL: http://eureka_client:eureka_password@sports-discovery:8761/eureka
#        PORT: 8381
#      depends_on:
#        - sports-postgres
#        - sports-discovery
#        - sports-config
#        - sports-gateway
#      profiles:
#        - cloud

