POST http://localhost:8080/api/v3/auth
Content-Type: application/json

{
  "username": "executorжека",
  "password": "executorжека",
  "nick": "executorжека",
  "telegram": "executorжека",
  "role": "EXECUTOR"
}
###

POST http://localhost:8080/api/v3/auth/tokens
Content-Type: application/json

{
  "username": "executorжека",
  "password": "executorжека"
}

###eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJleGVjdXRvcjIzIiwiaWQiOiIwZTk3NGM3YS00MDM3LTQ5NTktOGMwNy1iZWUzZmU1MmU5NDgiLCJyb2xlcyI6WyJFWEVDVVRPUiJdLCJleHAiOjE3MzczMDQyODB9.dZgFemgkhQPxV7oLHZ1lakpuTuaTAbv_QrLxrwknX-vvw85Uxh5SDNBSE5h_VzwHRb7zojJeogFbT3O_NulaMg

  "id": "c7958670-5895-4aef-bf01-2dbca3e155e2",
"username": "executor2",
"access": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJleGVjdXRvcjIiLCJpZCI6ImM3OTU4NjcwLTU4OTUtNGFlZi1iZjAxLTJkYmNhM2UxNTVlMiIsInJvbGVzIjpbIkVYRUNVVE9SIl0sImV4cCI6MTczMjQ4NDk5NX0.iC8e8O0cqApMysdjI-avOvJysbOK6S0g5I-ZB7v-e9OdnBb8YOcGTf-DZ5N--xnXyyase9bftK668ImeGcJeiQ",
"refresh": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJleGVjdXRvcjIiLCJpZCI6ImM3OTU4NjcwLTU4OTUtNGFlZi1iZjAxLTJkYmNhM2UxNTVlMiIsImV4cCI6MTczMjU2Nzc5NX0.FHJUB3pA1ZuXBlodTIbOw41eEBOLLCMBx3q_5fiETTHfMHGJ9IcP0fr_9IeOiBtEZ4ea1vdrsy2zQiAuZ8qIuQ"
}
###

POST http://localhost:8080/api/v3/performers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJleGVjdXRvctC20LXQutCwIiwiaWQiOiIyZTZhY2RmNi04NTNmLTQ2OTgtOTllZS1lNTZkY2VmZjdhNmYiLCJyb2xlcyI6WyJFWEVDVVRPUiJdLCJleHAiOjE3MzczMTM4MTd9.HVnCfJnyJvIckfyPGaDgVrSvUoXSQuRLpen8kFFyN8Yy8EIzpojfvDwIvqt5VgVXMssM62fk0kJ8v6yqiNp-Ng

{
  "email": "litvinowwa@mail.ru",
  "passportSeriesNumber": "11111",
  "weight": 10.00,
  "height": 150.0
}

###

POST http://localhost:8080/api/v3/fights
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJleGVjdXRvctC20LXQutCwIiwiaWQiOiIyZTZhY2RmNi04NTNmLTQ2OTgtOTllZS1lNTZkY2VmZjdhNmYiLCJyb2xlcyI6WyJFWEVDVVRPUiJdLCJleHAiOjE3MzczMTM4MTd9.HVnCfJnyJvIckfyPGaDgVrSvUoXSQuRLpen8kFFyN8Yy8EIzpojfvDwIvqt5VgVXMssM62fk0kJ8v6yqiNp-Ng

{
  "performerId": "a3181d68-7b3d-41a1-b8bd-eab32b690d7a",
  "orderId": "bf0bde33-b88d-4cd3-90c1-3400212964cf"
}

###
19c7344a-cfe8-4aab-9285-ee169d7b5e63


