POST http://localhost:8080/api/v2/auth
Content-Type: application/json

{
  "username": "executor2",
  "password": "executor2",
  "nick": "executor2",
  "telegram": "executor2",
  "role": "EXECUTOR"
}
###

POST http://localhost:8080/api/v2/auth/tokens
Content-Type: application/json

{
  "username": "executor2",
  "password": "executor2"
}

###

  "id": "c7958670-5895-4aef-bf01-2dbca3e155e2",
"username": "executor2",
"access": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJleGVjdXRvcjIiLCJpZCI6ImM3OTU4NjcwLTU4OTUtNGFlZi1iZjAxLTJkYmNhM2UxNTVlMiIsInJvbGVzIjpbIkVYRUNVVE9SIl0sImV4cCI6MTczMjQ4NDk5NX0.iC8e8O0cqApMysdjI-avOvJysbOK6S0g5I-ZB7v-e9OdnBb8YOcGTf-DZ5N--xnXyyase9bftK668ImeGcJeiQ",
"refresh": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJleGVjdXRvcjIiLCJpZCI6ImM3OTU4NjcwLTU4OTUtNGFlZi1iZjAxLTJkYmNhM2UxNTVlMiIsImV4cCI6MTczMjU2Nzc5NX0.FHJUB3pA1ZuXBlodTIbOw41eEBOLLCMBx3q_5fiETTHfMHGJ9IcP0fr_9IeOiBtEZ4ea1vdrsy2zQiAuZ8qIuQ"
}
###

POST http://localhost:8080/api/v2/performers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJleGVjdXRvcjIiLCJpZCI6IjdiMWY1YzdlLTM0ZjYtNGE0Mi04Mjc3LTY2MWE3YTFiOWVlNiIsInJvbGVzIjpbIkVYRUNVVE9SIl0sImV4cCI6MTczMjU1MDY2NX0._es6Of1ULg0GllD2DPXXoZ6UJyWzC6Wg_mnbtpPTrL6HbwaVBv9If8b133QrgdUPKCg9Xl5oMLEdll-G4rG0sQ


{
  "passportSeriesNumber": "11111",
  "weight": 100.00,
  "height": 180.0
}

###

POST http://localhost:8080/api/v2/fights
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJleGVjdXRvcjIiLCJpZCI6IjdiMWY1YzdlLTM0ZjYtNGE0Mi04Mjc3LTY2MWE3YTFiOWVlNiIsInJvbGVzIjpbIkVYRUNVVE9SIl0sImV4cCI6MTczMjU1MDY2NX0._es6Of1ULg0GllD2DPXXoZ6UJyWzC6Wg_mnbtpPTrL6HbwaVBv9If8b133QrgdUPKCg9Xl5oMLEdll-G4rG0sQ


{
  "performerId": "b611357e-f1d0-4561-8146-806ff0a7ebc1",
  "orderId": "acdf6448-9682-498e-a58e-b37d451826d5"
}

###


