POST http://localhost:8080/api/v2/auth
Content-Type: application/json

{
  "username": "executor2",
  "password": "executor2",
  "nick": "executor2",
  "telegram": "executor2",
  "role": "EXECUTOR"
}
###

POST http://localhost:8080/api/v2/auth/tokens
Content-Type: application/json

{
  "username": "executor2",
  "password": "executor2"
}

###

  "id": "c7958670-5895-4aef-bf01-2dbca3e155e2",
"username": "executor2",
"access": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJleGVjdXRvcjIiLCJpZCI6ImM3OTU4NjcwLTU4OTUtNGFlZi1iZjAxLTJkYmNhM2UxNTVlMiIsInJvbGVzIjpbIkVYRUNVVE9SIl0sImV4cCI6MTczMjQ4NDk5NX0.iC8e8O0cqApMysdjI-avOvJysbOK6S0g5I-ZB7v-e9OdnBb8YOcGTf-DZ5N--xnXyyase9bftK668ImeGcJeiQ",
"refresh": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJleGVjdXRvcjIiLCJpZCI6ImM3OTU4NjcwLTU4OTUtNGFlZi1iZjAxLTJkYmNhM2UxNTVlMiIsImV4cCI6MTczMjU2Nzc5NX0.FHJUB3pA1ZuXBlodTIbOw41eEBOLLCMBx3q_5fiETTHfMHGJ9IcP0fr_9IeOiBtEZ4ea1vdrsy2zQiAuZ8qIuQ"
}
###

POST http://localhost:8080/api/v2/performers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJleGVjdXRvcjIiLCJpZCI6IjcxNzVkYmE0LWFiODgtNDBlMy04YjUxLTdiNWFiOTJmMTYwNCIsInJvbGVzIjpbIkVYRUNVVE9SIl0sImV4cCI6MTczMjYwOTUyMH0.HZhh0Z_aCIEZFUT43eXfVoYWqFd4BTLZKU0jxSBmrpYsZGYK5Y_ChW4jhcBU4QvsXk4tIaIvyx0kxqH3Wf6lzQ


{
  "passport_series_number": "11111",
  "weight": 100.00,
  "height": 180.0
}

###

POST http://localhost:8080/api/v2/fights
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJleGVjdXRvcjIiLCJpZCI6IjcxNzVkYmE0LWFiODgtNDBlMy04YjUxLTdiNWFiOTJmMTYwNCIsInJvbGVzIjpbIkVYRUNVVE9SIl0sImV4cCI6MTczMjYwOTUyMH0.HZhh0Z_aCIEZFUT43eXfVoYWqFd4BTLZKU0jxSBmrpYsZGYK5Y_ChW4jhcBU4QvsXk4tIaIvyx0kxqH3Wf6lzQ


{
  "performer_id": "2b691f6c-fb86-445b-ae8b-fe00a12893f3",
  "order_id": "595694e2-5e33-4849-862f-2eb6d77ee1df"
}

###


