POST http://localhost:8080/api/v2/auth
Content-Type: application/json

{
  "username": "user1112",
  "password": "password1112",
  "nick": "user1112",
  "telegram": "user1112",
  "role": "EXECUTOR"
}

### Test for user registration

POST http://localhost:8080/api/v2/auth
Content-Type: application/json

{
  "username": "testuser",
  "password": "password123"
}


### Test for getting authorization details (authenticated request)

GET http://localhost:8080/api/v2/auth
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyMTExMiIsImlkIjoiN2JlZmIwYzktZjNhNS00ZDllLWJjOWMtOGI3OTU0ZDNlMzRjIiwicm9sZXMiOlsiRVhFQ1VUT1IiXSwiZXhwIjoxNzMyNDUxODczfQ.WI_CiwLMgQM5bR8B2OudV-04oCxVdOD7Er9lkiyNFiW1z6V2YKhiwMr1oC7K7_WOHLcNCELhk1NR1EOkU3epaA

###
 "access": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzdXBlcnVzZXIxIiwiaWQiOiIzNzM3MjQ0Ny1hY2MyLTRhMGUtYWNmOS1kZWYxN2I5NGZkODUiLCJyb2xlIjoiU1VQRVJWSVNPUiIsImV4cCI6MTczMjE4MTI3OH0.ORMFzWUS4zEzqFSNMvUTAkHZLgKEM9K6dfxgnCfFybl0IfQH-mNnkxEMwNOrMuuzQoSyekPsbO-_0lKg46Mxbg",
  "refresh": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzdXBlcnVzZXIxIiwiaWQiOiIzNzM3MjQ0Ny1hY2MyLTRhMGUtYWNmOS1kZWYxN2I5NGZkODUiLCJleHAiOjE3MzIyNjQwNzh9.va8VPC99qI8H-uoWxsmqJb-r5iRUVen6ge8FRGRm3NObL55guY65Qk64YE-NHp202plJfSnvb-fMRtDYwh8z9w"
}
### Test for user authorization (login)

POST http://localhost:8080/api/v2/auth/tokens
Content-Type: application/json

{
  "username": "user1112",
  "password": "password1112"
}


### Test for refreshing the authorization token

POST http://localhost:8080/api/v2/auth/tokens/refresh?refresh=<valid-refresh-token>
Authorization: Bearer <valid-access-token>

### Expected Response (Re-authorization)
HTTP/1.1 201 Created
Content-Type: application/json

{
  "accessToken": "<new-access-token>",
  "refreshToken": "<new-refresh-token>"
}

###
GET http://localhost:8080/api/v2/users/7befb0c9-f3a5-4d9e-bc9c-8b7954d3e34c
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyMTExMiIsImlkIjoiN2JlZmIwYzktZjNhNS00ZDllLWJjOWMtOGI3OTU0ZDNlMzRjIiwicm9sZXMiOlsiRVhFQ1VUT1IiXSwiZXhwIjoxNzMyNDUxODczfQ.WI_CiwLMgQM5bR8B2OudV-04oCxVdOD7Er9lkiyNFiW1z6V2YKhiwMr1oC7K7_WOHLcNCELhk1NR1EOkU3epaA

###
 "access": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzdXBlcnVzZXIxIiwiaWQiOiIzNzM3MjQ0Ny1hY2MyLTRhMGUtYWNmOS1kZWYxN2I5NGZkODUiLCJyb2xlIjoiU1VQRVJWSVNPUiIsImV4cCI6MTczMjE4MTc1N30.mdI8flT6TtJvGbAy4mLLDb4ij9gp3zZcDibxA5tTY_54eW8woynA5LB8MhgqCuiBr-QdxaHFA3b7BWoo-yv9Ew",
"refresh": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzdXBlcnVzZXIxIiwiaWQiOiIzNzM3MjQ0Ny1hY2MyLTRhMGUtYWNmOS1kZWYxN2I5NGZkODUiLCJleHAiOjE3MzIyNjQ1NTd9.PrJdaXApcnCR9GEETpNXN1cnc7NKfeGsAp9RzeGV_1CcWN9-QaY9pzT0y74o_HA93Mheze9o4jaCL_nFn_mnKA"
}
###

{
  "id": "449b74f5-9030-4c25-8562-7e740ad8cb03",
  "username": "superuser1",
  "role": [
    "SUPERVISOR"
  ]
}