info:
  app:
    name: sports-user
    description: User service
  team:
    name: D2 team

spring:
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE

  application:
    name: sports-user
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  r2dbc:
    properties:
      schema: application

  liquibase:
    liquibaseSchema: migration
    change-log: classpath:/db/changelog/master.yml

springdoc:
  api-docs:
    enabled: true
    path: /sports-user/v3/api-docs

server:
  port: ${PORT:8383}